site_name: PepperPy Console
site_description: A powerful Python library for building text-based user interfaces
site_author: PepperPy Team
repo_url: https://github.com/yourusername/pepperpy-console
repo_name: pepperpy-console

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - CLI System: cli/index.md
    - TUI Framework: tui/index.md
    - Theme System: themes/index.md
  - Examples: examples/index.md
  - API Reference: api/index.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/pepperpy-console
    - icon: fontawesome/brands/discord
      link: https://discord.gg/pepperpy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pepperpy-console/

copyright: Copyright &copy; 2024 PepperPy Team 