name: Documentation
on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.11'
        type: string
      docs-directory:
        description: 'Directory containing mkdocs.yml and docs/'
        required: false
        default: '.'
        type: string
    secrets:
      token:
        description: 'GitHub token for deployment'
        required: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dagger CLI
        uses: dagger/dagger-for-github@v5
        with:
          version: 'latest'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build and Deploy Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          cd pipelines/mkdocs/example
          go run main.go 